openapi: 3.0.0
info:
  title: TheHive Project API
  description: API for interacting with TheHive Project.
  version: 1.0.0
servers:
  - url: https://api.thehive.example.com
    description: TheHive API Server

paths:
  /v1/query:
    post:
      summary: Query Cases or Tasks
      description: Query for cases or tasks using various filters.
      operationId: queryCasesOrTasks
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: start_time
          in: query
          required: false
          schema:
            type: integer
      requestBody:
        description: Query parameters for listing cases or tasks.
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: Successful query
          content:
            application/json:
              schema:
                type: object
                properties:
                  cases:
                    type: array
                    items:
                      type: object
                  tasks:
                    type: array
                    items:
                      type: object
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /case/{case_id}:
    get:
      summary: Get Case
      description: Retrieve a specific case by ID.
      operationId: getCase
      parameters:
        - name: case_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful retrieval of case
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Case not found
        '500':
          description: Internal server error

    patch:
      summary: Update Case
      description: Update a specific case by ID.
      operationId: updateCase
      parameters:
        - name: case_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Fields to update in the case.
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful update of case
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Case not found
        '500':
          description: Internal server error

  /case:
    post:
      summary: Create Case
      description: Create a new case with the provided details.
      operationId: createCase
      requestBody:
        description: Details of the case to create.
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Successful creation of case
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /case/{case_id}/task:
    post:
      summary: Create Task
      description: Create a new task for a specific case.
      operationId: createTask
      parameters:
        - name: case_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Details of the task to create.
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Successful creation of task
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Case not found
        '500':
          description: Internal server error

  /case/task/{task_id}:
    patch:
      summary: Update Task
      description: Update a specific task by ID.
      operationId: updateTask
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Fields to update in the task.
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful update of task
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Task not found
        '500':
          description: Internal server error

    get:
      summary: Get Task
      description: Retrieve a specific task by ID.
      operationId: getTask
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful retrieval of task
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Task not found
        '500':
          description: Internal server error

components:
  schemas:
    Case:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        severity:
          type: string
        startDate:
          type: string
          format: date-time
        owner:
          type: string
        flag:
          type: string
        tlp:
          type: string
        tags:
          type: array
          items:
            type: string
        resolutionStatus:
          type: string
        impactStatus:
          type: string
        summary:
          type: string
        endDate:
          type: string
          format: date-time
        metrics:
          type: object
        status:
          type: string

    Task:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        flag:
          type: string
        status:
          type: string
        owner:
          type: string
